definitions:
  request.Notify:
    properties:
      organization:
        type: string
      phone:
        type: string
    type: object
info:
  contact: {}
paths:
  /:
    get:
      consumes:
      - application/json
      description: Hello World
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Hello
      tags:
      - Hello
  /Notify:
    post:
      consumes:
      - application/json
      description: Notify
      parameters:
      - description: payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/request.Notify'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Notify
      tags:
      - Notify
  /heartbeat:
    get:
      consumes:
      - application/json
      description: Heartbeat
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Heartbeat
      tags:
      - Heartbeat
swagger: "2.0"
