info:
  contact: {}
paths:
  /api/v2/troom/bulletin/IoMT_status:
    get:
      consumes:
      - application/json
      description: IoMT_status
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: IoMT_status
      tags:
      - IoMT_status
  /api/v2/troom/phone/IoMT_task:
    post:
      consumes:
      - application/json
      description: IoMT_task
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: IoMT_task
      tags:
      - IoMT_task
  /heartbeat:
    get:
      consumes:
      - application/json
      description: Heartbeat
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Heartbeat
      tags:
      - Heartbeat
swagger: "2.0"
